octomap_server:
  ros__parameters:
    frame_id: "world"
    resolution: 1.0

    height_map: false
    colored_map: false

    sensor_model:
      max_range: 25.0

    occupancy_min_z: -5.0
    occupancy_max_z: 30.0
